version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DOCKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/scripts/create.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
